name: macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies via Homebrew
      run: |
        brew update
        brew install cmake ninja qt@6

    - name: Set up environment for Qt
      run: |
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
        echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@6" >> $GITHUB_ENV

    - name: Configure with CMake
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build with Ninja
      run: |
        cmake --build build
        ls -a build
        otool -l build/ZipCombiner
        otool -L build/ZipCombiner
        
